# Generated by Django 3.0.3 on 2020-03-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaldoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True)),
                ('problem', models.CharField(choices=[('Solved', 'Solved'), ('Pending', 'Pending')], max_length=200, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Not Provided', 'Not Provided'), ('In Progress', 'In Progress'), ('Cancelled', 'Cancelled')], max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctors',
            name='fees',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
