# Generated by Django 3.0.3 on 2020-03-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaldoc', '0002_auto_20200303_0050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctors',
            new_name='doctor',
        ),
        migrations.AddField(
            model_name='solution',
            name='Add_solution',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
