# Generated by Django 3.0.3 on 2020-03-03 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personaldoc', '0003_auto_20200303_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personaldoc.doctor'),
        ),
        migrations.AddField(
            model_name='solution',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personaldoc.patient'),
        ),
    ]
