# Generated by Django 3.0.3 on 2020-03-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaldoc', '0005_auto_20200303_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='tags',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Qualifications',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='tags',
            field=models.ManyToManyField(to='personaldoc.Tag'),
        ),
    ]
