# Generated by Django 3.0.3 on 2020-03-04 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personaldoc', '0006_auto_20200303_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Add_solution', models.CharField(max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Not Provided', 'Not Provided'), ('In Progress', 'In Progress'), ('Cancelled', 'Cancelled')], max_length=200, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='doctor',
            new_name='Doctors',
        ),
        migrations.RenameModel(
            old_name='patient',
            new_name='Patients',
        ),
        migrations.DeleteModel(
            name='solution',
        ),
        migrations.AddField(
            model_name='solutions',
            name='Doctors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personaldoc.Doctors'),
        ),
        migrations.AddField(
            model_name='solutions',
            name='Patients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personaldoc.Patients'),
        ),
    ]
