# Generated by Django 3.0.3 on 2020-03-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaldoc', '0007_auto_20200304_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('In Progress', 'In Progress'), ('Cancelled', 'Cancelled')], max_length=200, null=True),
        ),
    ]
