# Generated by Django 3.0.3 on 2020-03-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaldoc', '0010_patients_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
