# Generated by Django 3.0.3 on 2020-03-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaldoc', '0012_auto_20200312_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='profile_pic',
            field=models.ImageField(blank=True, default='logo.png ', null=True, upload_to=''),
        ),
    ]
